
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Sends a packet to verify all dependencies mod versions are the same on connect. DIsable if it causes issues
	mod_version_check_packet = true
	#Don't touch unless you are told to
	debug_packet = false

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false

	#Disables certain types
	[general.types]

		[general.types.leaves_type]

			[general.types.leaves_type.biomesoplenty]
				origin = true
				flowering_oak = true
				maple = true
				orange_autumn = true
				yellow_autumn = true
				rainbow_birch = true
				snowblossom = true
				fir = true
				redwood = true
				mahogany = true
				jacaranda = true
				palm = true
				willow = true
				dead = true
				magic = true
				umbran = true
				hellbark = true

			[general.types.leaves_type.croptopia]
				cinnamon = true

			[general.types.leaves_type.aether]
				skyroot = true
				golden_oak = true
				crystal = true
				crystal_fruit = true
				holiday = true
				decorated_holiday = true

			[general.types.leaves_type.deeperdarker]
				echo = true

			[general.types.leaves_type.undergarden]
				smogstem = true
				wigglewood = true
				grongle = true

			[general.types.leaves_type.blue_skies]
				crystallized = true
				crescent_fruit = true
				bluebright = true
				starlit = true
				frostbright = true
				lunar = true
				dusk = true
				maple = true
				comet = true

		[general.types.wood_type]

			[general.types.wood_type.domum_ornamentum]
				cactus = true
				cactus_extra = true

			[general.types.wood_type.biomesoplenty]
				fir = true
				redwood = true
				mahogany = true
				jacaranda = true
				palm = true
				willow = true
				dead = true
				magic = true
				umbran = true
				hellbark = true

			[general.types.wood_type.aether]
				skyroot = true

			[general.types.wood_type.deeperdarker]
				echo = true

			[general.types.wood_type.undergarden]
				smogstem = true
				wigglewood = true
				grongle = true

			[general.types.wood_type.blue_skies]
				crystallized = true
				bluebright = true
				starlit = true
				frostbright = true
				lunar = true
				dusk = true
				maple = true
				comet = true

	#Disables specific entries
	[general.entries]

		[general.entries.wood_type]

			[general.entries.wood_type.farmersdelight]
				cabinet = true

			[general.entries.wood_type.create]
				window_pane = true
				window = true

			[general.entries.wood_type.mcwfurnitures]
				wardrobe = true
				stripped_glass_table = true
				stripped_desk = true
				modern_desk = true
				stripped_lower_bookshelf_drawer = true
				stripped_end_table = true
				end_table = true
				stool_chair = true
				drawer = true
				stripped_lower_triple_drawer = true
				stripped_bookshelf_drawer = true
				stripped_bookshelf = true
				modern_chair = true
				stripped_drawer_counter = true
				bookshelf_drawer = true
				chair = true
				stripped_table = true
				double_drawer = true
				stripped_coffee_table = true
				stripped_counter = true
				double_drawer_counter = true
				stripped_striped_chair = true
				covered_desk = true
				drawer_counter = true
				counter = true
				stripped_modern_chair = true
				bookshelf_cupboard = true
				table = true
				stripped_stool_chair = true
				stripped_modern_wardrobe = true
				cupboard_counter = true
				desk = true
				stripped_covered_desk = true
				coffee_table = true
				glass_table = true
				stripped_double_wardrobe = true
				stripped_cupboard_counter = true
				stripped_triple_drawer = true
				stripped_chair = true
				stripped_double_drawer = true
				stripped_double_drawer_counter = true
				triple_drawer = true
				lower_triple_drawer = true
				bookshelf = true
				stripped_wardrobe = true
				large_drawer = true
				stripped_modern_desk = true
				stripped_bookshelf_cupboard = true
				modern_wardrobe = true
				double_wardrobe = true
				stripped_drawer = true
				lower_bookshelf_drawer = true
				striped_chair = true
				stripped_large_drawer = true

			[general.entries.wood_type.mcwlights]
				soul_tiki_torch = true
				tiki_torch = true

			[general.entries.wood_type.mcwbridges]
				bridge_pier = true
				rope_bridge_stair = true
				log_bridge_stair = true
				rail_bridge = true
				rope_bridge = true
				log_bridge_middle = true

			[general.entries.wood_type.mcwpaths]
				planks_path = true

